<template>
  <loading v-bind:active="isLoading">
    <div class="loadingio-spinner-ellipsis-mzcrqlmja4">
      <div class="ldio-tt2ld1x659n">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </loading>
</template>

<script>
import Loading from 'vue-loading-overlay'
import 'vue-loading-overlay/dist/css/index.css'

export default {
  props: {
    isLoading: {
      type: Boolean,
      default: false
    }
  },

  components: {
    Loading
  }
}
</script>

  <style >
@keyframes ldio-tt2ld1x659n {
  0% {
    transform: translate(12px, 80px) scale(0);
  }
  25% {
    transform: translate(12px, 80px) scale(0);
  }
  50% {
    transform: translate(12px, 80px) scale(1);
  }
  75% {
    transform: translate(80px, 80px) scale(1);
  }
  100% {
    transform: translate(148px, 80px) scale(1);
  }
}
@keyframes ldio-tt2ld1x659n-r {
  0% {
    transform: translate(148px, 80px) scale(1);
  }
  100% {
    transform: translate(148px, 80px) scale(0);
  }
}
@keyframes ldio-tt2ld1x659n-c {
  0% {
    background: #ffb6bb;
  }
  25% {
    background: #ffe691;
  }
  50% {
    background: #95d5ee;
  }
  75% {
    background: #bbe7ba;
  }
  100% {
    background: #ffb6bb;
  }
}
.ldio-tt2ld1x659n div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  transform: translate(80px, 80px) scale(1);
  background: #ffb6bb;
  animation: ldio-tt2ld1x659n 1.36986301369863s infinite cubic-bezier(0, 0.5, 0.5, 1);
}
.ldio-tt2ld1x659n div:nth-child(1) {
  background: #bbe7ba;
  transform: translate(148px, 80px) scale(1);
  animation: ldio-tt2ld1x659n-r 0.3424657534246575s infinite cubic-bezier(0, 0.5, 0.5, 1),
    ldio-tt2ld1x659n-c 1.36986301369863s infinite step-start;
}
.ldio-tt2ld1x659n div:nth-child(2) {
  animation-delay: -0.3424657534246575s;
  background: #ffb6bb;
}
.ldio-tt2ld1x659n div:nth-child(3) {
  animation-delay: -0.684931506849315s;
  background: #bbe7ba;
}
.ldio-tt2ld1x659n div:nth-child(4) {
  animation-delay: -1.0273972602739727s;
  background: #95d5ee;
}
.ldio-tt2ld1x659n div:nth-child(5) {
  animation-delay: -1.36986301369863s;
  background: #ffe691;
}
.loadingio-spinner-ellipsis-mzcrqlmja4 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-tt2ld1x659n {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-tt2ld1x659n div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>