<template>
  <loading v-bind:active="isLoading">
    <div class="loadingio-spinner-ellipsis-ipzqzqz7enm">
      <div class="ldio-ufy7y4bqp8">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </loading>
</template>

<script>
import Loading from 'vue-loading-overlay'
import 'vue-loading-overlay/dist/css/index.css'

export default {
  props: {
    isLoading: {
      type: Boolean,
      default: false
    }
  },

  components: {
    Loading
  }
}
</script>

<style >
@keyframes ldio-ufy7y4bqp8 {
  0% {
    transform: translate(15.76px, 82.74px) scale(0);
  }
  25% {
    transform: translate(15.76px, 82.74px) scale(0);
  }
  50% {
    transform: translate(15.76px, 82.74px) scale(1);
  }
  75% {
    transform: translate(82.74px, 82.74px) scale(1);
  }
  100% {
    transform: translate(149.72px, 82.74px) scale(1);
  }
}
@keyframes ldio-ufy7y4bqp8-r {
  0% {
    transform: translate(149.72px, 82.74px) scale(1);
  }
  100% {
    transform: translate(149.72px, 82.74px) scale(0);
  }
}
@keyframes ldio-ufy7y4bqp8-c {
  0% {
    background: #e15b64;
  }
  25% {
    background: #59c5e5;
  }
  50% {
    background: #f8b26a;
  }
  75% {
    background: #abbd81;
  }
  100% {
    background: #e15b64;
  }
}
.ldio-ufy7y4bqp8 div {
  position: absolute;
  width: 31.52px;
  height: 31.52px;
  border-radius: 50%;
  transform: translate(82.74px, 82.74px) scale(1);
  background: #e15b64;
  animation: ldio-ufy7y4bqp8 1.4492753623188404s infinite cubic-bezier(0, 0.5, 0.5, 1);
}
.ldio-ufy7y4bqp8 div:nth-child(1) {
  background: #abbd81;
  transform: translate(149.72px, 82.74px) scale(1);
  animation: ldio-ufy7y4bqp8-r 0.3623188405797101s infinite cubic-bezier(0, 0.5, 0.5, 1),
    ldio-ufy7y4bqp8-c 1.4492753623188404s infinite step-start;
}
.ldio-ufy7y4bqp8 div:nth-child(2) {
  animation-delay: -0.3623188405797101s;
  background: #e15b64;
}
.ldio-ufy7y4bqp8 div:nth-child(3) {
  animation-delay: -0.7246376811594202s;
  background: #abbd81;
}
.ldio-ufy7y4bqp8 div:nth-child(4) {
  animation-delay: -1.0869565217391304s;
  background: #f8b26a;
}
.ldio-ufy7y4bqp8 div:nth-child(5) {
  animation-delay: -1.4492753623188404s;
  background: #59c5e5;
}
.loadingio-spinner-ellipsis-ipzqzqz7enm {
  width: 197px;
  height: 197px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-ufy7y4bqp8 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ufy7y4bqp8 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
